
package soap.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPSERVICE", targetNamespace = "http://soap/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SOAPSERVICE {


    /**
     * 
     * @param msg
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "crypted", partName = "crypted")
    @Action(input = "http://soap/SOAPSERVICE/cryptRequest", output = "http://soap/SOAPSERVICE/cryptResponse")
    public int crypt(
        @WebParam(name = "msg", partName = "msg")
        String msg);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap/SOAPSERVICE/bannerRequest", output = "http://soap/SOAPSERVICE/bannerResponse")
    public String banner();

}
